name: "Submit your article proposal"
description: Create a new content - Tutorial, Article
title: "[SUBMIT]"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for showing your interest in Write with Webiny program. Submit your proposal with a topic and an abstract using this form.

  - type: markdown
    attributes:
      label: Abstract
      value: |
        Please describe what you want to write about, how it would be relevant, and what format you would like to submit your article in (tutorial, guide, code example, blog...).
        Here is an example abstract outline.

  - type: textarea
    attributes:
        label: Introduction
        description: Sample Introduction - To-Do applications are a way of organizing things to do or achieve in the form of a list. This list allows us to write down tasks, reprioritize tasks more efficiently, and manage them for increased productivity.

  - type: textarea
    attributes:
        label: Goals
        description: In this article, we will learn about the Webiny CMS and how we can use it in a React application by working on building a To-Do app.

  - type: textarea
    attributes:
      label: Sample articles
      description: Please share any previously written articles that showcase your writing style.