name: "Submit your article proposal"
description: Create a new content - Tutorial, Article
title: "[SUBMIT]"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for showing your interest in Write with Webiny program. Submit your proposal with a topic and an abstract using this form.

  - type: textarea
    attributes:
      label: Introduction
      description: Please describe what you want to write about, below is a sample introduction.

        To-Do applications are a way of organizing things to do or achieve in the form of a list. This list allows us to write down tasks, reprioritize tasks more efficiently, and manage them for increased productivity.

  - type: textarea
    attributes:
      label: Goals
      description: Please explain goal of the article and how it would be relevant for the readers.
        Sample Goal - In this article, we will learn about the Webiny CMS and how we can use it in a React application by working on building a To-Do app.

  - type: textarea
    attributes:
      label: Outline
      description: Please let us know what format you would like to submit your article in (tutorial, guide, code example, blog...) and below is the sample outline for it

        - What is a Headless CMS?

        - Why use Webiny CMS?

        - Building a To-Do application?

          -- Installing dependencies

          -- Creating an input section

          -- Add To-Do list display

        - Setting up Webiny CMS

          -- Content Structure

          -- Connecting the CMS to the application

        - Creating, Updating, and Deleting To-Dos

        - Conclusion

        - Resources

  - type: textarea
    attributes:
      label: Sample articles
      description: Please share any previously written articles that showcase your writing style.