name: "Submit your article proposal"
description: Create a new content - Tutorial, Article
title: "[SUBMIT]"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for showing your interest in Write with Webiny program. Submit your proposal with a topic and an abstract using this form.
  - type: textarea
    attributes:
      label: Abstract
      description:
        Please describe what you want to write about, how it would be relevant, and what format you would like to submit your article in (tutorial, guide, code example, blog...).
        Here is an example abstract outline -   


        **Introduction**

        - To-Do applications are a way of organizing things to do or achieve in the form of a list. This list allows us to write down tasks, reprioritize tasks more efficiently, and manage them for increased productivity.


        **Goals**

        - In this article, we will learn about the Webiny CMS and how we can use this in a React application by working on building a to-do app.


        **Outline**

        - What is a Headless CMS?

        - Why use Webiny CMS?

        - Building a To-do application?

          -- Installing dependencies

          -- Creating an input section

          -- Add to-do list display

        - Setting up Webiny CMS

          -- Content Structure

          -- Connecting the CMS to the application

        - Creating, Updating, and Deleting to-dos

        - Conclusion

        - Resources

  - type: textarea
    attributes:
      label: Sample articles
      description: Please share any previously written articles that showcase your writing style.