name: "Request New Content"
description: Request for new content to be created by the Webiny community
title: "[Request New Content]"
body:
  - type: textarea
    attributes:
      label: Topic
      description: Please describe the topic on which you'd like the Webiny community to create content.
      value: | 
        <!--
          [Sample Outline]   
          I would like to see a tutorial on using Next.js with Webiny Headless CMS. Please cover the following topics in the tutorial:
          -- Setting up a Next.js project 
          -- Fetching the Content Entries using GraphQL APIs with Apollo Client
          -- How to use Next.js preview mode
        -->

        #### Community Vote
        👍 If you like this topic, please upvote it!