name: "Request New Content"
description: Request for new content to be created by the Webiny community
title: "[Request A New Content]"
body:
  - type: textarea
    attributes:
      label: Topic
      description: Please describe the topic on which you'd like the Webiny community to create content.