name: "Request new content"
description: Request for new content to be created by the Webiny community
title: "[Request new content AA]"
body:
  - type: textarea
    attributes:
      label: Topic
      description: Please describe the topic on which you'd like the Webiny community to create content.