name: "Request New Content"
description: Request for new content to be created by the Webiny community
title: "[Request New Content]"
body:
  - type: textarea
    attributes:
      label: Request New Content
      description: Please give a brief description of the topic you're interested in. 