name: "Request New Content"
description: Request for new content to be created by the Webiny community
title: "[Request New Content]"
body:
  - type: markdown
    attributes:
      value: |
        Please describe the topic on which you'd like the Webiny community to create content. 
  - type: textarea



      